"use client";

import React, { useState, useEffect, useRef } from "react";
import { createBrowserClient } from "@supabase/ssr";
import { useRouter } from "next/navigation";
import { toast } from 'sonner'; // For notifications
import { supabase } from "../../lib/supabaseClient";
import LoadingScreen from "../LoadingScreen";


interface AddTalentFormProps {
  onSuccess?: () => void; // Optional callback for success
  onClose: () => void; // Callback to close the modal
}

// Define the expected structure for a talent object in Supabase
interface Talent {
  id?: string; // UUID, auto-generated by Supabase
  first_name: string;
  last_name: string;
  city: string;
  specialty?: string;
 interview_url ?: string;
  image_url?: string; // Public URL of the uploaded image
  latitude: number;
  longitude: number;
  created_at?: string; // Timestamp, auto-generated by Supabase
}

// Define the structure for suggestions from api-adresse.data.gouv.fr
interface AddressSuggestion {
  city: string;
  postcode: string;
  geometry: {
    coordinates: [number, number]; // [longitude, latitude]
  };
  properties: { // Use properties for clearer access to city/postcode
    city: string;
    postcode: string;
  };
}

const AddTalentForm: React.FC<AddTalentFormProps> = ({ onSuccess, onClose }) => {
    const router = useRouter();
    const [formData, setFormData] = useState<Partial<Talent>>({
      first_name: "",
      last_name: "",
      city: "",
      specialty: "",
      interview_url: "",
    });
    const [imageFile, setImageFile] = useState<File | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [geocodeError, setGeocodeError] = useState<string | null>(null);
    const [cityQuery, setCityQuery] = useState('');
    const [suggestions, setSuggestions] = useState<any[]>([]);
    const [selectedCoordinates, setSelectedCoordinates] = useState<{lat: number, lng: number} | null>(null);
    const [isSuggestionsVisible, setIsSuggestionsVisible] = useState(false);
  
    const handleInputChange = (
      event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
    ) => {
      const { name, value } = event.target;
      setFormData((prev) => ({ ...prev, [name]: value }));
      // Clear geocoding error if city changes
      if (name === "city") {
        setGeocodeError(null);
      }
    };
  
    const handleImageChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      if (event.target.files && event.target.files[0]) {
        setImageFile(event.target.files[0]);
      } else {
        setImageFile(null);
      }
    };
  
   
  
    const handleImageUpload = async (): Promise<string | null> => {
      if (!imageFile) return null; // No image to upload
  
      // Generate a unique file name
      const fileExtension = imageFile.name.split('.').pop();
      const fileName = `${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExtension || 'png'}`;
      const bucketName = "talents-pics";
  
      try {
        const { error: uploadError } = await supabase.storage
          .from(bucketName)
          .upload(fileName, imageFile);
  
        if (uploadError) {
          throw uploadError;
        }
  
        // Get public URL - Supabase v2 API correction
        // The 'getPublicUrl' method now returns { data: { publicUrl: string } } directly.
        const { data } = await supabase.storage
          .from(bucketName)
          .getPublicUrl(fileName);
  
        // Directly return the publicUrl from data
        return data.publicUrl;
  
      } catch (err: any) {
        console.error("Image upload error:", err);
        setError(`Erreur lors de l'upload de l'image: ${err.message}`);
        return null;
      }
    };
  
    const fetchCitySuggestions = async (query: string) => {
    // 1. On change 'query.length < 3' par 'query.length < 1'
    if (query.length < 1) {
      setSuggestions([]);
      return;
    }
    
    try {
      // On garde un petit limit à 5 pour que la liste ne soit pas trop longue dès le début
      const response = await fetch(`https://api-adresse.data.gouv.fr/search/?q=${encodeURIComponent(query)}&type=municipality&limit=20`);
      const data = await response.json();
      setSuggestions(data.features || []);
      setIsSuggestionsVisible(true);
    } catch (error) {
      console.error("Erreur suggestions:", error);
    }
  };
  
    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
      event.preventDefault();
      setIsLoading(true);
      setError(null);
      window.scrollTo(0, 0); // On remonte tout en haut
      
  
      const { first_name, last_name, city, specialty, interview_url } = formData;
  
      // 1. Validation de base + Vérification des coordonnées
      if (!first_name || !last_name || !city) {
        setError("Les champs Prénom, Nom et Ville sont obligatoires.");
        setIsLoading(false);
        return;
      }
  
      // On bloque si l'utilisateur n'a pas cliqué sur une suggestion de la liste
      if (!selectedCoordinates) {
        setError("Veuillez sélectionner une ville dans la liste suggérée pour obtenir sa position GPS.");
        setIsLoading(false);
        return;
      }
  
      try {
        // 2. Upload de l'image si elle existe
        let imageUrl: string | null = null;
        if (imageFile) {
          imageUrl = await handleImageUpload();
          if (!imageUrl) {
            // L'erreur est déjà gérée dans handleImageUpload via setError
            setIsLoading(false);
            return;
          }
        }
  
        // 3. Préparation des données finales pour Supabase
        // On utilise les coordonnées stockées lors du clic sur l'autocomplétion
        const newTalent = {
          first_name,
          last_name,
          city,
          specialty: specialty || null,
          interview_url: interview_url || null,
          image_url: imageUrl,
          latitude: selectedCoordinates.lat,
          longitude: selectedCoordinates.lng,
        };
  
        // 4. Enregistrement dans la table 'talents'
        const { error: dbError } = await supabase
          .from("talents")
          .insert([newTalent]);
  
        if (dbError) {
          throw dbError;
        }
  
        // Succès : Redirection
        router.push("/"); // Ou "/admin/talents" selon ta structure
        router.refresh(); // Force la mise à jour de la carte sur l'accueil
  
      } catch (err: any) {
        console.error("Erreur globale lors de la soumission:", err);
        setError(`Une erreur est survenue : ${err.message}`);
      } finally {
        setIsLoading(false);
      }
    };
    

  return (
    <form onSubmit={handleSubmit}>
  {isLoading && <LoadingScreen />}
  
  {/* Prénom */}
  <div>
    <label htmlFor="first_name" className="block text-sm font-semibold uppercase mb-2">Prénom *</label>
    <input
      type="text"
      id="first_name"
      name="first_name"
      value={formData.first_name}
      onChange={handleInputChange}
      required
      placeholder="ex: Jean"
      className="w-full p-3 bg-black border border-zinc-700 rounded focus:border-yellow-500 focus:ring-1 focus:ring-yellow-500 outline-none transition-all text-white"
    />
  </div>

  {/* Nom */}
  <div>
    <label htmlFor="last_name" className="block text-sm font-semibold uppercase mb-2 mt-4">Nom *</label>
    <input
      type="text"
      id="last_name"
      name="last_name"
      value={formData.last_name}
      onChange={handleInputChange}
      required
      placeholder="ex: Dupont"
      className="w-full p-3 bg-black border border-zinc-700 rounded focus:border-yellow-500 focus:ring-1 focus:ring-yellow-500 outline-none transition-all text-white"
    />
  </div>

  {/* Ville (Autocomplétion) */}
  <div className="relative">
    <label className="block text-sm font-semibold uppercase mb-2 mt-4">Ville *</label>
    <input
      type="text"
      value={cityQuery}
      onChange={(e) => {
        setCityQuery(e.target.value);
        fetchCitySuggestions(e.target.value);
      }}
      required
      className="w-full p-3 bg-black border border-zinc-700 rounded focus:border-yellow-500 focus:ring-1 focus:ring-yellow-500 outline-none transition-all text-white"
      placeholder="Rechercher une ville..."
    />
    
    {isSuggestionsVisible && suggestions.length > 0 && (
      <ul className="absolute left-0 right-0 mt-1 bg-zinc-900 border border-yellow-500 rounded shadow-2xl z-[9999] max-h-60 overflow-y-auto">
        {suggestions.map((s, index) => (
          <li
            key={index}
            onClick={() => {
              setCityQuery(s.properties.label);
              setSelectedCoordinates({
                lng: s.geometry.coordinates[0],
                lat: s.geometry.coordinates[1]
              });
              setFormData({ ...formData, city: s.properties.city });
              setIsSuggestionsVisible(false);
            }}
            className="p-3 hover:bg-yellow-500 hover:text-black cursor-pointer text-white border-b border-zinc-800 transition-colors"
          >
            {s.properties.label} <span className="text-xs opacity-60">({s.properties.postcode})</span>
          </li>
        ))}
      </ul>
    )}
  </div>

  {/* Spécialité principale */}
<div className="space-y-2 mt-4">
  <label className="block text-sm font-semibold uppercase mb-2">Spécialité principale *</label>
  <select 
    value={formData.specialty}
    onChange={(e) => setFormData({...formData, specialty: e.target.value})}
    required
    /* Dynamisme de la couleur : gris si vide, blanc si sélectionné */
    className={`w-full bg-black border border-zinc-700 rounded p-3 outline-none focus:border-yellow-500 focus:ring-1 focus:ring-yellow-500 transition-all ${
      !formData.specialty ? "text-zinc-500" : "text-white"
    }`}
  >
    {/* On met cette option en 'disabled' pour qu'elle ne soit plus sélectionnable une fois qu'on a choisi */}
    <option value="" disabled className="text-zinc-500">Sélectionnez une catégorie</option>
    
    {/* On force le texte des options en blanc pour contrer le style du parent */}
    <option value="mode" className="text-white bg-zinc-900">Mode / Design</option>
    <option value="sport" className="text-white bg-zinc-900">Sport / Fitness</option>
    <option value="musique" className="text-white bg-zinc-900">Musique / Art</option>
    <option value="media" className="text-white bg-zinc-900">Média / Influence</option>
    <option value="tech" className="text-white bg-zinc-900">Tech / Digital</option>
    <option value="entrepreneuriat" className="text-white bg-zinc-900">Entrepreneuriat</option>
  </select>
</div>

  {/* URL interview */}
  <div>
    <label htmlFor="interview_url" className="block text-sm font-semibold uppercase mb-2 mt-4">Lien Interview</label>
    <input
      type="url"
      id="interview_url"
      name="interview_url"
      value={formData.interview_url}
      onChange={handleInputChange}
      placeholder="https://..."
      className="w-full p-3 bg-black border border-zinc-700 rounded focus:border-yellow-500 focus:ring-1 focus:ring-yellow-500 outline-none transition-all text-white"
    />
  </div>

  {/* Photo du Talent */}
  <div className="pt-2 mt-4">
    <label className="block text-sm font-semibold uppercase mb-3 text-yellow-500">Photo du Profil *</label>
    <div className="flex items-center justify-center w-full">
      <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-zinc-700 border-dashed rounded-lg cursor-pointer bg-black hover:bg-zinc-900 hover:border-yellow-500 transition-all">
        <div className="flex flex-col items-center justify-center pt-5 pb-6">
          <p className="mb-2 text-sm text-zinc-400">
            <span className="font-semibold text-white">Cliquez pour uploader *</span>
          </p>
          <p className="text-xs text-zinc-500">PNG, JPG ou WEBP</p>
        </div>
        <input 
          type="file" 
          className="hidden" 
          accept="image/*"
          onChange={handleImageChange}
          required={!formData.image_url} // Requis uniquement s'il n'y a pas déjà d'image
        />
      </label>
    </div>
    {imageFile && (
      <p className="text-xs mt-2 text-yellow-500 font-medium italic">
        Fichier sélectionné : {imageFile.name}
      </p>
    )}
  </div>

 <button
    
    type="submit"
    // Désactivé si : chargement OU pas de ville OU pas de prénom OU pas de nom OU pas de spécialité
    disabled={
      isLoading || 
      !selectedCoordinates || 
      !formData.first_name || 
      !formData.last_name || 
      !formData.specialty ||
      !imageFile
    }
    className="w-full py-4 px-4 mt-8 rounded-md shadow-lg text-lg font-bold uppercase tracking-wider text-black bg-yellow-500 hover:bg-yellow-400 active:scale-95 focus:outline-none focus:ring-2 focus:ring-yellow-600 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
  >
    {isLoading ? "Enregistrement en cours..." : "Valider le profil"}
  </button>
</form>
    
  
);
};

export default AddTalentForm;
