import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar"; // Import the Navbar component
import { Toaster } from "sonner"; // Import Toaster from sonner
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "BLK RADAR",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico?v=3",
    shortcut: "/favicon.ico?v=3",
    apple: "/favicon.ico?v=3",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 `}
      >
        <Suspense fallback={<div className="h-20 bg-black" />}>
          <Navbar />
        </Suspense>
        <main className="pt-20">
          {" "}
          {/* Add padding-top to prevent content from going under the fixed Navbar */}
          {children}
        </main>
        <Toaster position="top-center" richColors />{" "}
        {/* Render the Toaster for global notifications */}
      </body>
    </html>
  );
}
